version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      sh -c "python manage.py makemigrations &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - dronerental-network
    depends_on:
      - db
    env_file:
       - ./.env

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dronerental
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - dronerental-network
  
  nginx:
    image: nginx:alpine
    container_name: rental_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - static_volume:/usr/src/rental/static/
    ports:
      - "80:80" 
    networks:
      - dronerental-network
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
    

networks:
  dronerental-network: